.SECONDEXPANSION:
.PHONY: all clean debug release


TST_DIRS = standards

all:
	for i in $(TST_DIRS); do \
		(cd $$i && echo "making $$i" && $(MAKE) ) || exit 1; \
	done

clean:
	for i in $(TST_DIRS); do \
		(cd $$i && echo "cleaning $$i" && $(MAKE) clean ) || exit 1; \
	done
